import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#2e56c5',
        'primary-fixed': '#ffdf9a',
        'on-primary-container': '#6c5100',
        'on-secondary': '#ffffff',
        outline: '#807662',
        'on-surface': '#1f1b13',
        'on-secondary-container': '#743900',
        'secondary-fixed': '#ffdcc5',
        'on-secondary-fixed-variant': '#713700',
        'surface-container-high': '#f1e7d9',
        'secondary-fixed-dim': '#ffb783',
        'tertiary-container': '#bcc9ff',
        'on-error': '#ffffff',
        'surface-container-highest': '#ebe1d3',
        secondary: '#924c0b',
        error: '#ba1a1a',
        'on-background': '#1f1b13',
        'surface-dim': '#e2d9cb',
        'on-tertiary-fixed-variant': '#043cad',
        'tertiary-fixed-dim': '#b5c4ff',
        'on-tertiary-container': '#224cbc',
        'surface-variant': '#ebe1d3',
        primary: '#775a00',
        'primary-container': '#f6c445',
        'on-surface-variant': '#4e4635',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#f1c041',
        background: '#fff8f2',
        'inverse-primary': '#f1c041',
        'on-error-container': '#93000a',
        'outline-variant': '#d2c5ae',
        'inverse-surface': '#353026',
        surface: '#fff8f2',
        'inverse-on-surface': '#f9efe1',
        'secondary-container': '#fea35e',
        'surface-container': '#f6edde',
        'on-tertiary-fixed': '#00164e',
        'surface-container-low': '#fcf2e4',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#301400',
        'on-primary-fixed': '#251a00',
        'surface-tint': '#775a00',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-bright': '#fff8f2',
        'tertiary-fixed': '#dce1ff',
        'on-primary-fixed-variant': '#5a4300',
        'workload-low': '#e6f4ea',
        'workload-mod': '#fff3cd',
        'workload-busy': '#ffe5b4',
        'workload-high': '#f8d7da',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        xs: '0.5rem',
        xl: '5rem',
        unit: '8px',
        md: '2rem',
        lg: '3rem',
        'container-margin': '24px',
        gutter: '20px',
        sm: '1rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero-mobile': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'label-caps': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'display-hero': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
      },
    },
  },
  plugins: [forms, containerQueries],
};
